### ISSUE TITLE
Bump to a SRCREV that doesn't cause segfaults

### ISSUE THREAD

**Issue by einoj** [rauc/meta-rauc#157]
This revision of rauc-hawkbit-updater causes segfaults https://github.com/rauc/rauc-hawkbit-updater/issues/21 
https://github.com/rauc/meta-rauc/blob/e9e0efe8591dfdb9fdef3191193d113cf9d20088/recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb#L8

I would at least bump to the revision that fixes this segfault, possibly a even newer one. https://github.com/rauc/rauc-hawkbit-updater/commit/7b97849e20a158cc140c5e49d2b8194ea965cf5e

It is a problem that rauc-hawkbit-updater do not crate tags for stable commits. I have opened an isue with them about that https://github.com/rauc/rauc-hawkbit-updater/issues/60

**Comment by ejoerns** [comment]
As I noted in #158, we should move to the latest master commit.

Yes, in general I agree that rauc-hawkbit-updater should be tagged. However, currently, there is no distinct state that I would call 'stable'. But it evolves into more overall stability with the latest fixes applied. Thus maybe we are getting closer to a point where it makes sense to do the initial commit. We would have to discuss this in https://github.com/rauc/rauc-hawkbit-updater/issues/60.
