### ISSUE TITLE
bundle.bbclass uses obsolte bb.build.funcfailed

### ISSUE THREAD

**Issue by MartinH76761** [rauc/meta-rauc#162]
bundle.bbclass uses obsolete failure function:
`raise bb.build.FuncFailed('Unable to open manifest.raucm')`

According to Wiki Yoctoproject FuncFailed is deprecated with 3.0, see https://wiki.yoctoproject.org/wiki/FutureMigrationGuide section "Bitbake changes".

Use bb.fatal() instead, example: https://github.com/openembedded/openembedded-core/commit/efe87ce4b2154c6f1c591ed9d8f770c229b044ad

**Comment by ejoerns** [comment]
@MartinH76761 Thanks for the report! Always feel free to just make a PR for those things if you find the time and like to contribute ;)

@Emantor Thanks for fixing!
