### ISSUE TITLE
do_bundle/do_deploy is slow when using Casync

### ISSUE THREAD

**Issue by om26er** [rauc/meta-rauc#194]
The `do_bundle` and subsequently `do_deploy` step are very slow and they seems to take quite a few minutes, I am not sure about the reason why it's slow.

My basic testing suggests that running `casync make` is a quick task, so I wonder what takes all that time ?

**Comment by ejoerns** [comment]
It calls `rauc bundle` and then `rauc convert`. This includes redundant signing. Could you check if running these commands manually after each other is quicker than the `do_bundle` task?

**Comment by ejoerns** [comment]
Closed due to inactivity. Feel free to reopen if this becomes relevant again.
