### ISSUE TITLE
How to pass PEM password to meta-rauc?

### ISSUE THREAD

**Issue by twinning92** [rauc/meta-rauc#200]
I am getting this error when attempting to bundle, I am unable to find where to pass the password in for the key.pem file.

```
ERROR: cube-bundle-1.0-r0 do_bundle: Execution of '/home/user/poky/build/tmp/work/poky-linux-gnueabi/cube-bundle/1.0-r0/temp/run.do_bundle.9897' failed with exit code 1:
rauc-Message: 02:55:39.491: Debug log domains: 'rauc'
(rauc:9900): rauc-DEBUG: 02:55:39.491: bundle start
(rauc:9900): rauc-DEBUG: 02:55:39.492: system config not found, using default values
(rauc:9900): rauc-DEBUG: 02:55:39.492: input directory: /home/user/poky/build/tmp/work/poky-linux-gnueabi/cube-bundle/1.0-r0/bundle
(rauc:9900): rauc-DEBUG: 02:55:39.492: output bundle: /home/user/poky/build/tmp/work/poky-linux-gnueabi/cube-bundle/1.0-r0/build/bundle.raucb
(rauc:9900): rauc-DEBUG: 02:55:41.372: Payload size: 53411840 bytes.
Creating bundle in 'plain' format
Enter PEM pass phrase:
Failed to create bundle: failed to sign bundle: failed to parse key file '/home/user/fapl-dev-certs/ee-cube/private/ee-cube.key': while reading strings
140324263220032:error:0906406D:PEM routines:PEM_def_callback:problems getting password:../openssl-1.1.1l/crypto/pem/pem_lib.c:59:
140324263220032:error:0906A068:PEM routines:PEM_do_header:bad password read:../openssl-1.1.1l/crypto/pem/pem_lib.c:434:
WARNING: exit code 1 from a shell command.
```

It's almost a certainty there are more things wrong with what I'm doing, this is the first time I'm playing with RAUC/yocto in general. I just can't get past this error to start whack-a-moleing the next errors.

I've looked around but I'm unable to find the variable to put this file in.

Thanks, and apologies if I've missed something obvious

**Comment by ejoerns** [comment]
Note that https://github.com/rauc/rauc/pull/945 now adds support for passing PEM passphrase via environment.

Will be part of RAUC 1.8.

**Comment by ejoerns** [comment]
RAUC 1.8 is now merged in meta-rauc `master` and `kirkstone`.

The environment variable could be passed into bitbake by setting `BB_ENV_PASSTHROUGH` or `BB_ENV_PASSTHROUGH_ADDITIONS`. The alternative to look at meta-code-signing was already mentioned.

@twinning92 I would consider this done first of all, if open questions remain, feel free to reopen / reply.
