### ISSUE TITLE
Linux Capability preservation of binaries

### ISSUE THREAD

**Issue by twinning92** [rauc/meta-rauc#208]
Hi,

I'm wondering if anyone can assist me in finding my missing capabilities! 

When I build and flash the wic file to our device, capabilities are present. When I build and bundle the same image (except in tar), then install using rauc on the target, the capabilities disappear.

I've extracted the rauc bundle after generation and inspected the relevant binaries, there are no caps set. So I'm guessing it has to do with tar or squashfs?

**Comment by ejoerns** [comment]
@twinning92 Have you resolved this in the meantime?

RAUC itself shouldn't do anything with the file system. And during `meta-rauc`'s bundle folder preparation, the artifacts are just copied. Thus my assumption is that the capability settings were removed from the file system *before* putting it into the bundle.
