### ISSUE TITLE
error with update bundles : "Signature size exceeds bundle size"

### ISSUE THREAD

**Issue by ddommerdich** [rauc/meta-rauc#235]
Hi,
I' m using RAUC to update a device. When i tried to install a bundle on my client device I 've got the following error message

> Signature size (7957085066972967886) exceeds bundle size

I first tried to print the information via the `rauc -d info` command but to no avail as it displayed the same message

I' ve then installed the RAUC tool on my computer and tried the same command and it worked perfectly

I checked in etc/rauc if the certificate was the same as the one in my layer and both were indeed the same
 
note : 

-  I am working with version "dunfell:2fe17af894b82cd2b0d0203478d4924fa916b440"
-  I am using Hawkbit with `rauc-hawkbit-updater`
-  I' ve generated the certificates with the openssl script provided by the meta-rauc layer
-  My machine has not enough RAM onboard so I am temporarily using a directory located on an SD card

Thank you in advance, I have already tested rauc with raspberry and i appreciate your tool

**Comment by Bastian-Krause** [comment]
"Signature size [..] exceeds bundle size" happens typically if the bundle is corrupt, or maybe not written completely, yet.

Can you elaborate on your scenario a bit more? rauc-hawkbit-updater writes the bundle to a file system on your SD card? And it triggers the installation?

**Comment by ddommerdich** [comment]
Thanks for the rapid reply.
So, my bad, as you said the download wasn't complete, i used the command rauc-hawkbit-updater -d and the thing is i didn't saw the progress status, just the debug message saying he was trying to reload.  So i falsely concluded that the download was completed. For anyone interested in monitoring progress of an update you can use this command `journalctl --follow -u rauc-hawkbit-updater` [as explained in this page](https://askubuntu.com/questions/1284378/how-to-see-live-status-changes-of-a-systemctl-service) 
thanks again for the support
