### ISSUE TITLE
casync failed to fetch 

### ISSUE THREAD

**Issue by qorinator** [rauc/meta-rauc#236]
Hi

it looks like that there is no more master branch in casync repo. I saw that in master, the SRC_URI branch has been changed to main. However kirkstone and honister still have the branch in master.

Regards,
Qorin

**Comment by ejoerns** [comment]
honister is EOL but kirkstone and dunfell require the patch, indeed.

**Comment by ejoerns** [comment]
I've backported the fix to kirkstone branch.

**Comment by qorinator** [comment]
Nice. Thanks!

I will just create a bbappend file for now then. Until I can update to kirkstone.

**Comment by ejoerns** [comment]
Since the fix was cherry-picked to `dunfell` LTS, too, I guess we can close this.
