### ISSUE TITLE
RDepend on minimal dt-utils-barebox-state version

### ISSUE THREAD

**Issue by leiflm** [rauc/meta-rauc#27]
In Relation to [this](https://github.com/rauc/rauc/pull/187) rauc issue, there should be a conditional `RDEPENDS` on `dt-utils >= v2017.03`. Afaik bitbake supports version specification for runtime dependencies.

**Comment by ejoerns** [comment]
Hm, meta-rauc provides dt-utils in the version required, don't you think this should be sufficient? I do not know any example of a version-specific RDEPEND in oe-core or similar.

**Comment by leiflm** [comment]
> Hm, meta-rauc provides dt-utils in the version required, don't you think this should be sufficient?

Current `HEAD` does. But e.g. the `morty`-branch does not. I think there should be a backport there? Or, alternatively a backported version enforcement. As I was working on introducing `meta-rauc` provided bundles, I wanted to try its HEAD. That didn't work OTB with the rest of my setup, so i decided to go back to a labled stated (`morty`), which silently broke `barebox-state`. I set the `PREFERRED_VERSION_dt-utils` in my distro.conf, but the warning about unavailability was silenced after the first run -.-' and went unnoticed.

On the other hand, providing a version doesn't enforce it. So a BSP provider might have a `PREFERRED_VERSION_dt-utils = x.y` due to other reasons. RAUC will build but won't work as expected during runtime.

**Comment by ejoerns** [comment]
AFAIK `PREFERRED_VERSION` does not allow a minimal version, but just a fixed one. Thus I find it inappropriate for this issue.
Additionally, it is only the simple truth that RAUC requires dt-utils v2017.03. It more or less depends on your storage type *and* more important, the Barebox (state) version you are using. Thus we also need to specify a minimum barebox version, etc.
Well, having a v2017.03 in morty sounds appropriate. The rest I am not really convinced of, yet.

**Comment by leiflm** [comment]
> AFAIK `PREFERRED_VERSION` does not allow a minimal version, but just a fixed one. Thus I find it inappropriate for this issue.

I don't think it's a solution either. My tried to point out that a BSP provider might set another (older) `PREFERRED_VERSION_dt-utils` in her `distro.conf`. This will go unnoticed.

About specifying versions using `RDEPENDS`, there was [a mail](https://lists.yoctoproject.org/pipermail/yocto/2013-August/015429.html) about it on the yocto ML.

**Comment by ejoerns** [comment]
@leiflm history showed that there are more than a single pitfall where dt-utils and barebox implementation potentially do not match. Thus I fear we cannot state any specific version.

Anyway, morty should be obsolete in most cases now and hopefully hardy anyone is still using it.

By default I would say meta-rauc defines the version to use. If there are good reasons we need a backport of newer dt-utils and pretty sure it will not break other things (trickiest part) I would choose this as the valid option.

@leiflm What do you think, can we close this?

**Comment by leiflm** [comment]
fair enough.
