### ISSUE TITLE
When IMAGE_NAME_SUFFIX is non standard a bundle will "fail to find sources"

### ISSUE THREAD

**Issue by Gerry546** [rauc/meta-rauc#299]
Currently `bundle.bbclass` assumes that [IMAGE_NAME_SUFFIX ](https://docs.yoctoproject.org/ref-manual/variables.html?highlight=extra_#term-IMAGE_NAME_SUFFIX) is using the default value of  `.rootfs`.
If you change IMAGE_NAME_SUFFIX to something else an error will be reported when building the bundle.

**Comment by ejoerns** [comment]
@Gerry546 You're right, I've created #300 to address this. Thanks!
