### ISSUE TITLE
Time to create `scarthgap` branch?

### ISSUE THREAD

**Issue by moto-timo** [rauc/meta-rauc#310]
Now that [meta-openembedded](https://git.openembedded.org/meta-openembedded/log/?h=scarthgap) has created the `scarthgap` branch, we are seeing [failures in layerindex updates](https://layers.openembedded.org/layerindex/updates/39587/) because there is no `scarthgap` branch for `meta-rauc`.

**Comment by AndreasUfert** [comment]
Would like to see a scarthgap branch as well. Currently using master in scarthgap projects which works fine already.

**Comment by ejoerns** [comment]
Thanks for the hint, I've created a [scarthgap](https://github.com/rauc/meta-rauc/tree/scarthgap) branch now. First of all in sync with `master`.
