### ISSUE TITLE
rauc-native [kirkstone] requires "nostamp" flag in some circumstances

### ISSUE THREAD

**Issue by rbenet** [rauc/meta-rauc#317]
We have an issue with `rauc-native` under `kirkstone` branch.

For the case where there is no sstate and no workspace the current code seems to work.
For the case where there is sstate and workspace is mantained between jobs seems to work.
For the case where there is sstate but the workspace is empty, then `rauc` does not get installed under `tmp/deploy/tools`.

If we add (via .bbappend)  the following line:
`do_deploy[nostamp]="1"`

then it all seems to work.
I see that more recent version of `rauc-native.inc` are simpler. I tried just implanting them on our kirkstone checkout, but it didn't had the desired effect. So, I am sticking with the `nostamp` approach for the moment.

https://github.com/rauc/meta-rauc/blob/1ce846097f74acfdd15fef0d64a6fd3eeee3d6f5/recipes-core/rauc/rauc-native.inc

**Comment by ejoerns** [comment]
@rbenet Thank you for reporting.

I'd not like to touch the deploy handling anymore if possible since this is not really recommended to use, anyway.
I've created https://github.com/rauc/meta-rauc/pull/319 to suggest using `oe-run-native` instead. Would this be sufficient for you?
