### ISSUE TITLE
Enhancement: add rauc-hawkbit-client service

### ISSUE THREAD

**Issue by hpatriarche** [rauc/meta-rauc#54]
As enhancement, it would be nice to install a rauc-hawkbit-client.service that start this application via systemd.

**Comment by ejoerns** [comment]
@hpatriarche `SYSTEMD_AUTO_ENABLE = "enable"` is default, thus we don't need it.

The rest looks fine for me. Would you like to make a PR of it? (Sorry for leaving this untouched so long)

**Comment by mschwan-phytec** [comment]
I think this gets resolved by #108.

**Comment by ejoerns** [comment]
And merged now. So we can close this here, too. Thx!
