### ISSUE TITLE
add rauc 1.0 support in sumo branch

### ISSUE THREAD

**Issue by thekyz** [rauc/meta-rauc#63]
As the title says, I'm a bit reluctant on using the master branch and we need 1.0 for full uboot support.

**Comment by ejoerns** [comment]
@thekyz I would see the latest 2 poky release still under maintenance as potential candidates for adding 1.0 support. Thus would include sumo and thud.

It was the plan to add this, anyway. But I wanted to have support in master first before backporting it to older versions.

**Comment by thekyz** [comment]
Great; do you have an ETA then?

**Comment by ejoerns** [comment]
ETA is ASAP :)

Will talk to @jluebbe how it will be added.

**Comment by ejoerns** [comment]
Fixed by manually PR #67 to sumo branch, too.
